import type { NextPage } from 'next';
import Head from 'next/head';
import styles from './styles/Home.module.scss';

interface AppLayoutProps {
  children: React.ReactNode;
  pageTitle: string;
}

const AppLayout: NextPage<AppLayoutProps> = ({ pageTitle, children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.deptagency.com/wp-content/themes/dept/public/favicon.svg"
        />
        <link
          href="http://fonts.cdnfonts.com/css/maison-neue"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default AppLayout;
